/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a09a7f6b-975c-41ac-8312-394f5125f922",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_EjdikH2Fm",
    "aws_user_pools_web_client_id": "25odu05lh56h8aqgljag0j9a52",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mtuujqeq7rczjmj3ek52ty4m7u.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
