/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faCamera,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faCloudSun,
    faColumns,
    faDoorOpen,
    faEllipsisV,
    faFan,
    faSearch,
    faSun,
    faTable,
    faTachometerAlt,
    faUser,
    faSync,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faCloudSun,
    faCamera,
    faDoorOpen,
    faEllipsisV,
    faFan,
    faSun,
    faSync,
};
